[workspace]
members = ["beer-api", "beer-domain", "beer-image", "beer-score", "beer-storage"]
resolver = "2"

[workspace.dependencies]
axum = "0.8"
axum-extra = { version = "0.12", features = ["cookie", "multipart"] }
base64 = "0.23.1"
beer-domain = { path = "beer-domain" }
beer-image = { path = "beer-image" }
beer-score = { path = "beer-score" }
beer-storage = { path = "beer-storage" }
bcrypt = "0.19.3"
cookie = "0.18"
dotenvy = "0.15"
nanoid = "0.5"
rand = "0.10.2"
rust-s3 = { version = "0.37", default-features = false, features = [
  "tokio-rustls-tls",
] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.11.0"
sqlx = { version = "0.9", features = [
  "runtime-tokio",
  "sqlite",
  "macros",
  "migrate",
] }
thiserror = "2"
tokio = { version = "1", features = [
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
] }
tower = "0.5"
tower-http = { version = "0.7.1", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
