INSERT OR IGNORE INTO drink_type (id, name, description, created_at, abv, multiplier) VALUES
    ('beer', 'Øl', 'Alle typer øl og ølbaserte drikker', unixepoch(), 5, 1.0),
    ('strong_beer', 'Sterk øl', 'Sterkøl og kraftige øltyper', unixepoch(), 8, 1.0),
    ('wine', 'Vin', 'Rødvin, hvitvin og musserende', unixepoch(), 12, 0.9),
    ('cocktail', 'Cocktail', 'Blandede drinker og cocktails', unixepoch(), 15, 0.75),
    ('shot', 'Shot', 'Shots og snaps', unixepoch(), 40, 1.0),
    ('liquor', 'Brennevin', 'Whisky, vodka, gin og andre sterke drikker', unixepoch(), 40, 1.0),
    ('cider', 'Cider', 'Eple- og pærecider', unixepoch(), 5, 1.0);

INSERT OR IGNORE INTO drink_size (id, name, volume_ml, description, created_at) VALUES
    ('beer_small', '0,33L', 330, 'Liten øl', unixepoch()),
    ('beer_medium', '0,4L', 400, 'Medium øl', unixepoch()),
    ('beer_large', '0,5L', 500, 'Stor øl', unixepoch()),
    ('beer_pint', 'Pint', 568, 'Engelsk pint', unixepoch()),
    ('beer_huge', '1L', 1000, 'Liter øl', unixepoch()),
    ('beer_jug', 'Mugge', 2400, 'Mugge med øl', unixepoch()),
    ('wine_glass', 'Et glass', 150, 'Standard vinglass', unixepoch()),
    ('wine_large_glass', 'Stort glass', 200, 'Stort vinglass', unixepoch()),
    ('wine_bottle', 'Flaske', 750, 'Hel flaske vin', unixepoch()),
    ('shot_standard', 'Shot', 40, 'Standard shot', unixepoch()),
    ('shot_double', 'Dobbel shot', 80, 'Dobbel shot', unixepoch()),
    ('cocktail_small', 'Liten drink', 200, 'Liten cocktail', unixepoch()),
    ('cocktail_standard', 'Standard drink', 300, 'Standard cocktail', unixepoch()),
    ('liquor_shot', 'Shot', 40, 'Shot brennevin', unixepoch()),
    ('liquor_double', 'Dobbel', 80, 'Dobbel brennevin', unixepoch()),
    ('liquor_glass', 'Glass', 100, 'Glass brennevin', unixepoch()),
    ('cider_small', '0,33L', 330, 'Liten cider', unixepoch()),
    ('cider_large', '0,5L', 500, 'Stor cider', unixepoch());

INSERT OR IGNORE INTO drink_type_size (id, drink_type_id, drink_size_id, created_at) VALUES
    ('beer_small_combo', 'beer', 'beer_small', unixepoch()),
    ('beer_medium_combo', 'beer', 'beer_medium', unixepoch()),
    ('beer_large_combo', 'beer', 'beer_large', unixepoch()),
    ('beer_pint_combo', 'beer', 'beer_pint', unixepoch()),
    ('beer_huge_combo', 'beer', 'beer_huge', unixepoch()),
    ('beer_jug_combo', 'beer', 'beer_jug', unixepoch()),
    ('strong_beer_small_combo', 'strong_beer', 'beer_small', unixepoch()),
    ('strong_beer_medium_combo', 'strong_beer', 'beer_medium', unixepoch()),
    ('strong_beer_large_combo', 'strong_beer', 'beer_large', unixepoch()),
    ('strong_beer_pint_combo', 'strong_beer', 'beer_pint', unixepoch()),
    ('strong_beer_huge_combo', 'strong_beer', 'beer_huge', unixepoch()),
    ('strong_beer_jug_combo', 'strong_beer', 'beer_jug', unixepoch()),
    ('wine_glass_combo', 'wine', 'wine_glass', unixepoch()),
    ('wine_large_glass_combo', 'wine', 'wine_large_glass', unixepoch()),
    ('wine_bottle_combo', 'wine', 'wine_bottle', unixepoch()),
    ('shot_standard_combo', 'shot', 'shot_standard', unixepoch()),
    ('shot_double_combo', 'shot', 'shot_double', unixepoch()),
    ('cocktail_small_combo', 'cocktail', 'cocktail_small', unixepoch()),
    ('cocktail_standard_combo', 'cocktail', 'cocktail_standard', unixepoch()),
    ('liquor_shot_combo', 'liquor', 'liquor_shot', unixepoch()),
    ('liquor_double_combo', 'liquor', 'liquor_double', unixepoch()),
    ('liquor_glass_combo', 'liquor', 'liquor_glass', unixepoch()),
    ('cider_small_combo', 'cider', 'cider_small', unixepoch()),
    ('cider_large_combo', 'cider', 'cider_large', unixepoch());
